language: php
php:
  - '5.6'

before_script:
- composer install

script:
- phpunit --configuration phpunit.xml

before_install:
- openssl aes-256-cbc -K $encrypted_31cc0dab49b8_key -iv $encrypted_31cc0dab49b8_iv -in travis-ssh-key.enc -out travis-ssh-key -d


addons:
  ssh_known_hosts:
  - tools.adfc-hamburg.de

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/travis-ssh-key
- ssh-add $TRAVIS_BUILD_DIR/travis-ssh-key
- chmod 750 $TRAVIS_BUILD_DIR/script/deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: $TRAVIS_BUILD_DIR/script/deploy.sh
  on:
    all_branches: true

after_deploy:
- eval "$(ssh-agent -ks)"
